### ISSUE TITLE
error while training

### ISSUE THREAD

**Issue by mhfatemi** [cyun-404/PieESRGAN#2]
![Screenshot (39)](https://user-images.githubusercontent.com/98775697/188062866-fd53d852-ba24-429a-a09e-e0e317b8427a.png)
I faced an error when start training in colab. I want to train from scratch but code need to "p-best.pth" file

**Comment by cyun-404** [comment]
Download weights
[Google Driver](https://drive.google.com/file/d/1SBxMk3ofuA217MaNhN71buf94aMDvH7a/view?usp=sharing)
in this link(in ReadMe), you can get "p-best.pth". While test, this file will be used. ("p-best.pth" is the result of the train)
